//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.API.CustomerWebService.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.API.CustomerWebService.Localization.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be empty bill id list.
        /// </summary>
        public static string BillsNotFound {
            get {
                return ResourceManager.GetString("BillsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card information is not found.
        /// </summary>
        public static string CardInformationNotFound {
            get {
                return ResourceManager.GetString("CardInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact phone no not found.
        /// </summary>
        public static string ContactPhoneNoNotFound {
            get {
                return ResourceManager.GetString("ContactPhoneNoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer e-mail address not found..
        /// </summary>
        public static string CustomerMailNotFound {
            get {
                return ResourceManager.GetString("CustomerMailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-archive pdf not found.
        /// </summary>
        public static string EArchivePDFNotFound {
            get {
                return ResourceManager.GetString("EArchivePDFNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card has active auto payment. Firstly, remove auto payment from card.
        /// </summary>
        public static string HasActiveAutoPayment {
            get {
                return ResourceManager.GetString("HasActiveAutoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Cashier Pays.
        /// </summary>
        public static string HasCashierPays {
            get {
                return ResourceManager.GetString("HasCashierPays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bill State.
        /// </summary>
        public static string InvalidBillState {
            get {
                return ResourceManager.GetString("InvalidBillState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation.
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Amount.
        /// </summary>
        public static string InvalidPaymentAmount {
            get {
                return ResourceManager.GetString("InvalidPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add card is deactive.
        /// </summary>
        public static string MobileExpressIsDeactive {
            get {
                return ResourceManager.GetString("MobileExpressIsDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Credit.
        /// </summary>
        public static string NotEnoughCredit {
            get {
                return ResourceManager.GetString("NotEnoughCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null object error.
        /// </summary>
        public static string NullObjectFound {
            get {
                return ResourceManager.GetString("NullObjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only One Gateway Allowed.
        /// </summary>
        public static string OnlyOneGatewayAllowed {
            get {
                return ResourceManager.GetString("OnlyOneGatewayAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionPaidType is required.
        /// </summary>
        public static string PaidTypeNull {
            get {
                return ResourceManager.GetString("PaidTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have payment permission.
        /// </summary>
        public static string PaymentPermissionNotFound {
            get {
                return ResourceManager.GetString("PaymentPermissionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota information not found.
        /// </summary>
        public static string QuotaNotFound {
            get {
                return ResourceManager.GetString("QuotaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer don&apos;t have quota tariff.
        /// </summary>
        public static string QuotaTariffNotFound {
            get {
                return ResourceManager.GetString("QuotaTariffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed. Registration is not possible with reference number..
        /// </summary>
        public static string SpecialOfferError {
            get {
                return ResourceManager.GetString("SpecialOfferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber not found.
        /// </summary>
        public static string SubscriberNotFound {
            get {
                return ResourceManager.GetString("SubscriberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support request is not found.
        /// </summary>
        public static string SupportRequestNotFound {
            get {
                return ResourceManager.GetString("SupportRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff not found.
        /// </summary>
        public static string TariffNotFound {
            get {
                return ResourceManager.GetString("TariffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom credentials not found.
        /// </summary>
        public static string TelekomCredentialsNotFound {
            get {
                return ResourceManager.GetString("TelekomCredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom web service error.
        /// </summary>
        public static string TelekomWebServiceError {
            get {
                return ResourceManager.GetString("TelekomWebServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS validation is failed.
        /// </summary>
        public static string WrongSMSValidation {
            get {
                return ResourceManager.GetString("WrongSMSValidation", resourceCulture);
            }
        }
    }
}
